### PR TITLE
adding filter and tests

### PR DESCRIPTION
**Pull request by rgritti**

### CODE REVIEW

**Comment by danpersa** [comment]
@rgritti could you add an example on how to use the filter here: https://github.com/zalando-incubator/skrop/blob/master/eskip/sample.eskip

**Comment by danpersa** [comment]
@rgritti And also in the readme file?

**Comment by rgritti** [comment]
@danpersa  done :+1:

**Comment by danpersa** [comment]
:+1

**Comment by danpersa** [comment]
👍

**Pull request merged**
